authapp/urls.py
from django.urls import path, re_path
from authapp import views, ajax_views

app_name = 'authapp'

urlpatterns = [
    #
    # re_path(r'^$', views.accounts, name='accounts'),
    #
    # re_path(r'^email/key/send/$', views.email_key_send, name='email_key_send'),
    re_path(r'^email/key/confirm/(?P<uid>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.primary_email_key_confirm, name='primary_email_key_confirm'),
    re_path(r'^password/reset/$', views.password_reset, name='password_reset'),
    re_path(r'^password/reset/key/confirm/(?P<uid>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.password_reset_key_confirm, name='password_reset_key_confirm'),
    re_path(r'^password/change/$', views.password_change, name='password_change'),
    # re_path(r'^deactivate/$', views.deactivate_user, name='deactivate_user'),
    re_path(r'^delete/$', views.delete_user, name='delete_user'),
    re_path(r'^settings/$', views.settings, name='settings'),
    # re_path(r'^settings/other/$', views.settings_other, name='settings_other'),

    re_path(r'^logout/$', views.log_out, name='log_out'),
    # re_path(r'^crop/$', views.crop, name='crop'),

    re_path(r'^email_ask/$', views.email_ask, name='email_ask'),
    # re_path(r'^test7/$', views.test7, name='test7'),

    # ------------------------------------------------------------------------------

    # re_path(r'^logout/$', views.log_out, name='log_out'),
    #
    # re_path(r'^username/change/$', views.username_change, name='username_change'),
    #
    # re_path(r'^password/change/$', views.password_change, name='password_change'),
    # re_path(r'^password/reset/$', views.password_reset, name='password_reset'),
    #
    # re_path(r'^email/add/$', views.email_add, name='email_add'),
]
'''
    url(r'^create/$', views.main_create_log_in, name='create'),
'''

baseapp/urls.py
from django.urls import path, re_path
from authapp import views as authviews
from authapp import ajax_views as auth_ajax_views
from baseapp import ajax_views as base_ajax_views
from baseapp import views
from django.views.generic import TemplateView
from baseapp.sitemaps import sitemaps
from django.contrib.sitemaps import views as sitemap_views
app_name = 'baseapp'

urlpatterns = [
    re_path(r'^robots\.txt$',
            TemplateView.as_view(template_name="others/robots.txt", content_type="text/plain"), name="robots"),
    path('a/sitemap.xml', sitemap_views.index, {'sitemaps': sitemaps, 'sitemap_url_name': 'baseapp:sitemaps'}),
    path('a/sitemap-<section>.xml', sitemap_views.sitemap, {'sitemaps': sitemaps},
         name='sitemaps'),
    re_path(r'^$', authviews.main_create_log_in, name='main_create_log_in'),

    re_path(r'^register/url/$', views.register_url, name='register_url'),
    re_path(r'^update/url/(?P<uuid>([0-9a-f]{32}))/$', views.update_url, name='update_url'),
    re_path(r'^object/(?P<uuid>([0-9a-f]{32}))/$', views.suobj, name='suobj'),
    re_path(r'^url/(?P<uuid>([0-9a-f]{32}))/$', views.url, name='url'),

    re_path(r'^(?P<user_username>([A-Za-z0-9_](?:(?:[A-Za-z0-9_]|(?:\.(?!\.))){0,28}(?:[A-Za-z0-9_]))?))/$',
            views.user_profile, name='user_profile'),

    re_path(r'^search/all/$', views.search_all, name='search_all'),
    re_path(r'^search/my/$', views.search_my, name='search_my'),
    re_path(r'^search/user/$', views.search_user, name='search_user'),
    re_path(r'^search/bridge/$', views.search_bridge, name='search_bridge'),
    re_path(r'^search/keyword/$', views.search_keyword, name='search_keyword'),
    re_path(r'^search/url/$', views.search_url, name='search_url'),

    re_path(r'^bridge/feed/$', views.bridge_feed, name='bridge_feed'),
    re_path(r'^note/all/$', views.note_all, name='note_all'),

    re_path(r'^(?P<user_username>([A-Za-z0-9_](?:(?:[A-Za-z0-9_]|(?:\.(?!\.))){0,28}(?:[A-Za-z0-9_]))?))/search/$',
            views.user_search, name='user_search'),
    # re_path(r'^note/all/$', views.note_all, name='note_all'),



    re_path(r'^re_settings/ajax/$', auth_ajax_views.re_settings, name='re_settings'),
    re_path(r'^re_settings/ajax/upload_user_photo/$', auth_ajax_views.upload_user_photo, name='re_upload_user_photo'),
    # re_path(r'^re/create/new/$', base_ajax_views.re_create_new, name='re_create_new'),

    re_path(r'^re/check/url/$', base_ajax_views.re_check_url,
            name='re_check_url'),
    re_path(r'^re/register/url/$', base_ajax_views.re_register_url,
            name='re_register_url'),
    re_path(r'^re/update/url/$', base_ajax_views.re_update_url,
            name='re_update_url'),
    re_path(r'^re/update/complete/url/$', base_ajax_views.re_update_complete_url,
            name='re_update_complete_url'),
    re_path(r'^re/refresh/url/$', base_ajax_views.re_refresh_url,
            name='re_refresh_url'),

    re_path(r'^re/profile/suobj/$', base_ajax_views.re_profile_suobj,
            name='re_profile_suobj'),
    re_path(r'^re/suobj/populate/$', base_ajax_views.re_suobj_populate,
            name='re_suobj_populate'),


    re_path(r'^re/bridge/add/$', base_ajax_views.re_bridge_add,
            name='re_bridge_add'),
    re_path(r'^re/bridging/list/$', base_ajax_views.re_bridging_list,
            name='re_bridging_list'),
    re_path(r'^re/bridger/list/$', base_ajax_views.re_bridger_list,
            name='re_bridger_list'),
    re_path(r'^re/help/list/$', base_ajax_views.re_help_list,
            name='re_help_list'),
    re_path(r'^re/url/populate/$', base_ajax_views.re_url_populate,
            name='re_url_populate'),

    re_path(r'^re/url/keyword/$', base_ajax_views.re_url_keyword,
            name='re_url_keyword'),

    re_path(r'^re/url/keyword/up/$', base_ajax_views.re_url_keyword_up,
            name='re_url_keyword_up'),
    re_path(r'^re/url/keyword/down/$', base_ajax_views.re_url_keyword_down,
            name='re_url_keyword_down'),

    re_path(r'^re/suobj/help/$', base_ajax_views.re_suobj_help,
            name='re_suobj_help'),

    re_path(r'^re/comment/add/$', base_ajax_views.re_comment_add,
            name='re_comment_add'),
    re_path(r'^re/comment/delete/$', base_ajax_views.re_comment_delete,
            name='re_comment_delete'),
    re_path(r'^re/comment/more/load/$', base_ajax_views.re_comment_more_load,
            name='re_comment_more_load'),

    re_path(r'^re/profile/suobj/delete/$', base_ajax_views.re_profile_suobj_delete,
            name='re_profile_suobj_delete'),

    re_path(r'^re/search/all/$', base_ajax_views.re_search_all,
            name='re_search_all'),
    re_path(r'^re/search/my/$', base_ajax_views.re_search_my,
            name='re_search_my'),

    re_path(r'^re/search/user/$', base_ajax_views.re_search_user,
            name='re_search_user'),
    re_path(r'^re/search/bridge/$', base_ajax_views.re_search_bridge,
            name='re_search_user'),
    re_path(r'^re/search/keyword/$', base_ajax_views.re_search_keyword,
            name='re_search_user'),
    re_path(r'^re/search/url/$', base_ajax_views.re_search_url,
            name='re_search_user'),

    re_path(r'^re/nav/badge/populate/$', base_ajax_views.re_nav_badge_populate,
            name='re_nav_badge_populate'),

    re_path(r'^re/note/all/$', base_ajax_views.re_note_all,
            name='re_note_all'),

    re_path(r'^re/bridge/feed/$', base_ajax_views.re_bridge_feed,
            name='re_bridge_feed'),
    re_path(r'^re/home/$', base_ajax_views.re_home,
            name='re_home'),

    re_path(r'^re/user/search/suobj/$', base_ajax_views.re_user_search_suobj,
            name='re_user_search_suobj'),
    re_path(r'^re/user/search/keyword/$', base_ajax_views.re_user_search_keyword,
            name='re_user_search_keyword'),
    # re_path(r'^re/follow/add/$', base_ajax_views.re_follow_add,
    #         name='re_follow_add'),
    # re_path(r'^re/following/list/$', base_ajax_views.re_following_list,
    #         name='re_following_list'),
    # re_path(r'^re/follower/list/$', base_ajax_views.re_follower_list,
    #         name='re_follower_list'),
    #
    # re_path(r'^re/profile/post/$', base_ajax_views.re_profile_post,
    #         name='re_profile_post'),
    # re_path(r'^re/post/populate/$', base_ajax_views.re_post_populate,
    #         name='re_post_populate'),
    # re_path(r'^email/key/send/$', views.email_key_send, name='email_key_send'),
    # re_path(r'^email/key/confirm/(?P<uid>([A-Za-z0-9_](?:(?:[A-Za-z0-9_]|(?:\.(?!\.))){0,28}(?:[A-Za-z0-9_]))?))/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        # views.email_key_confirm, name='email_key_confirm'),
    # re_path(r'^logout/$', views.log_out, name='log_out'),
    # re_path(r'^username/change/$', views.username_change, name='username_change'),
    # re_path(r'^password/change/$', views.password_change, name='password_change'),
    # re_path(r'^password/reset/$', views.password_reset, name='password_reset'),
    # re_path(r'^email/add/$', views.email_add, name='email_add'),
]
'''
    url(r'^create/$', views.main_create_log_in, name='create'),
'''

pagepik/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    re_path(r'^accounts/', include('authapp.urls')),
    re_path(r'^', include('baseapp.urls')),
]


from django.views.generic import TemplateView
# 이 아래부분 미디어 파일 디벨롭모드에서 쓰기 위해 필요
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        # path('admin/', admin.site.urls),
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
        re_path(r'^a/admin/', admin.site.urls),
    ]

baseapp/models.py
from django.db import models

# Create your models here.

baseapp/forms.py
from django import forms
from object.models import Post, PostProfile, PostChatPhoto


class PostCreateForm(forms.ModelForm):

    whose = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'whose'}))
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'name'}), required=False)
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'title'}))
    description = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'description'}))
    title_content = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'title_content'}), required=False)
    description_content = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'description_content'}), required=False)

    class Meta:
        model = Post
        fields = ['whose', 'name', 'description', 'title_content', 'description_content']


class PostProfilePhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    rotate = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = PostProfile
        fields = ('file_300', 'file_50', 'x', 'y', 'width', 'height', 'rotate',)


class PostChatPhotoForm(forms.ModelForm):
    rotate = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = PostChatPhoto
        fields = ('file', 'rotate',)

baseapp/views.py
from django.shortcuts import render, redirect, reverse
from relation.models import *
from object.models import *
from object.numbers import *
from notice.models import *
from django.db.models import Q
from django.db import transaction
import uuid

from django.utils.timezone import now, timedelta

# Create your views here.









def register_url(request):
    if request.method == "GET":
        if not request.user.is_authenticated:
            return redirect(reverse('baseapp:main_create_log_in'))
        return render(request, 'baseapp/register_url.html')


def update_url(request, uuid):
    if request.method == "GET":
        if not request.user.is_authenticated:
            return redirect(reverse('baseapp:main_create_log_in'))
        sub_url_object = None
        try:
            sub_url_object = SubUrlObject.objects.get(uuid=uuid, user=request.user)
        except Exception as e:
            return redirect(reverse('baseapp:main_create_log_in'))
        return render(request, 'baseapp/update_url.html', {'id': uuid})


def user_profile(request, user_username):
    if request.method == "GET":
        if request.user.is_authenticated:
            user = None
            try:
                chosen_user = User.objects.get(userusername__username=user_username)
            except Exception as e:
                return render(request, '404.html')
            if chosen_user is not None:
                bridging = None
                if Bridge.objects.filter(user=request.user, bridge=chosen_user).exists():
                    bridging = True

                return render(request, 'baseapp/user_profile.html', {'chosen_user': chosen_user, 'bridging': bridging})
        else:
            user = None
            try:
                chosen_user = User.objects.get(userusername__username=user_username)
            except Exception as e:
                return render(request, '404.html')
            if chosen_user is not None:
                bridging = None
                return render(request, 'baseapp/user_profile.html',
                              {'chosen_user': chosen_user, 'bridging': bridging})


def suobj(request, uuid):
    if request.method == "GET":
        suobj = None
        try:
            suobj = SubUrlObject.objects.get(uuid=uuid)
        except:
            return render(request, '404.html')
        if suobj is not None:
            return render(request, 'baseapp/suobj.html', {'id': uuid})

        return render(request, '404.html')


def url(request, uuid):
    if request.method == "GET":
        url_object = None
        try:
            url_object = UrlObject.objects.get(uuid=uuid)
        except:
            return render(request, '404.html')
        if url_object is not None:
            return render(request, 'baseapp/url.html', {'url_object': url_object, 'id': uuid})

        return render(request, '404.html')



def search_all(request):
    if request.method == "GET":
        q = request.GET.get('q', None)
        if q is None:
            q = ''
        q = q.strip()
        word = q
        return render(request, 'baseapp/search_all.html', {'word': word})

# 브릿지 검색아래 제네럴 검색


def search_user(request):
    if request.method == "GET":
        q = request.GET.get('q', None)
        if q is None:
            q = ''
        q = q.strip()
        word = q
        return render(request, 'baseapp/search_user.html', {'word': word})


def search_my(request):
    if request.method == "GET":
        if not request.user.is_authenticated:
            return redirect(reverse('baseapp:main_create_log_in'))
        q = request.GET.get('q', None)
        if q is None:
            q = ''
        q = q.strip()
        word = q
        return render(request, 'baseapp/search_my.html', {'word': word})


def search_bridge(request):
    if request.method == "GET":
        if not request.user.is_authenticated:
            return redirect(reverse('baseapp:main_create_log_in'))
        q = request.GET.get('q', None)
        if q is None:
            q = ''
        q = q.strip()
        word = q
        return render(request, 'baseapp/search_bridge.html', {'word': word})


def search_keyword(request):
    if request.method == "GET":
        q = request.GET.get('q', None)
        if q is None:
            q = ''
        q = q.strip()
        word = q
        return render(request, 'baseapp/search_keyword.html', {'word': word})


def search_url(request):
    if request.method == "GET":
        q = request.GET.get('q', None)
        if q is None:
            q = ''
        q = q.strip()
        word = q
        return render(request, 'baseapp/search_url.html', {'word': word})


def note_all(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            try:
                with transaction.atomic():
                    notices_update = Notice.objects.filter(Q(user=request.user) & Q(checked=False)).update(
                        checked=True)
                    notice_count = request.user.noticecount
                    notice_count.count = 0
                    notice_count.save()
            except Exception as e:
                print(e)
                pass
            return render(request, 'baseapp/note_all.html')
        else:
            return redirect(reverse('baseapp:main_create_log_in'))


def bridge_feed(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            return render(request, 'baseapp/bridge_feed.html')
        else:
            return redirect(reverse('baseapp:main_create_log_in'))


def user_search(request, user_username):
    if request.method == "GET":
        q = request.GET.get('q', None)
        if q is None:
            q = ''
        q = q.strip()
        word = q
        try:
            chosen_user = User.objects.get(userusername__username=user_username)
        except Exception as e:
            return render(request, '404.html')
        return render(request, 'baseapp/user_search.html', {'word': word, 'chosen_user': chosen_user})

baseapp/templates/baseapp/_modal_bridge.html
<div class="modal fade" id="modal_bridging">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div align="center">bridging</div>
                <div id="modal_bridging_list">

                </div>
                <a href="">
                    <div class="hidden more_load" align="center" id="modal_bridging_more">more</div>
                </a>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal_bridger">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div align="center">bridgers</div>
                <div id="modal_bridger_list">

                </div>
                <a href="">
                    <div class="hidden more_load" align="center" id="modal_bridger_more">more</div>
                </a>
            </div>
        </div>
    </div>
</div>
<div class="hidden" id="next_user_id"></div>
<div class="modal fade" id="modal_need_login_bridge">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <div align="center">need to login</div>
            <a href="{% url 'baseapp:main_create_log_in' %}"><div align="center" class="clickable modal_need_login_select">login / sign up</div></a>
        </div>
      </div>
    </div>
</div>

baseapp/templates/baseapp/_modal_no_keyword.html
<div class="modal fade" id="modal_register">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <div class="h4" align="center">There is no keyword, is it okay?</div>
            <a href=""><div align="center" class="clickable register_yes" id="pass_register">Yes</div></a>
            <a href=""><div align="center" class="clickable register_cancel" data-dismiss="modal">Cancel</div></a>
        </div>

      </div>
    </div>
</div>

baseapp/templates/baseapp/_modal_populate.html
<div class="hidden" id="clicked_suobj_id"></div>
<div class="hidden" id="next_user_id"></div>

<div class="modal fade" id="modal_pop_menu">
    <div class="modal-dialog modal-dialog_menu">
        <div class="modal-content modal-content_menu">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body modal_pop_menu_body" id="modal_pop_menu_content">
                <div align="center">
                    <input type="text" id="modal_pop_menu_input" class="modal_pop_menu_input">
                </div>
                <div align="center" class="modal_pop_menu_link_wrapper">
                    <a href=""><span class="clickable modal_pop_menu_copy" id="modal_pop_menu_copy">copy link</span></a>
                </div>
                <div align="center" class="modal_pop_menu_link_wrapper">
                    <a href=""><span class="clickable modal_pop_menu_locate"
                                     id="modal_pop_menu_locate">move to link</span></a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal_need_login_pop">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div align="center">need to login</div>
                <a href="{% url 'baseapp:main_create_log_in' %}">
                    <div align="center" class="clickable modal_need_login_select">login / sign up</div>
                </a>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal_help">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div align="center">helped</div>
                <div id="modal_help_list">

                </div>
                <a href="">
                    <div class="hidden" align="center" id="modal_help_more">more</div>
                </a>
            </div>
        </div>
    </div>
</div>

baseapp/templates/baseapp/_navbar.html
<nav class="navbar navbar-default navbar-fixed-top navbar_base">
    <div class="container-fluid padding_right_0">
        <ul class="nav navbar-nav navbar_ul_base">
            <li>
                {% if user.is_authenticated %}
                    <a class="padding_15_i" id="a_home" href="/">
                        <i id="i_home" class="glyphicon glyphicon-home"></i>
                    </a>
                {% else %}
                    <a class="padding_15_i" id="a_home" href="{% url 'baseapp:main_create_log_in' %}">
                        <i id="i_home" class="glyphicon glyphicon-home"></i>
                    </a>
                {% endif %}
            </li>
            <li>
                {% if user.is_authenticated %}
                    <a class="padding_15_i" id="a_feed" href="{% url 'baseapp:bridge_feed' %}">
                        <i id="i_feed" class="glyphicon glyphicon-comment"></i>
                    </a>
                {% else %}
                    <a class="padding_15_i" id="a_feed" href="{% url 'baseapp:main_create_log_in' %}">
                        <i id="i_feed" class="glyphicon glyphicon-comment"></i>
                    </a>
                {% endif %}
            </li>
            <li>

                {% if user.is_authenticated %}
                    <a class="padding_15_i" id="a_user" href="/{{ user.userusername.username }}/">
                        <i id="i_user" class="glyphicon glyphicon-user"></i>
                    </a>
                {% else %}
                    <a class="padding_15_i" id="a_user" href="{% url 'baseapp:main_create_log_in' %}">
                        <i id="i_user" class="glyphicon glyphicon-user"></i>
                    </a>
                {% endif %}

            </li>

            <li id="nav_div_ul_li_bsearch">

                {% if user.is_authenticated %}
                    {% if user.noticecount.count == 0 %}
                        <a class="padding_15_i" id="a_note" href="{% url 'baseapp:note_all' %}">
                            <i id="i_note" class="glyphicon glyphicon-certificate"></i>
                        </a>
                    {% else %}
                        <a class="padding_15_i" id="a_note" href="{% url 'baseapp:note_all' %}">
                            <span id="i_note" class="nav_note_count">{{ user.noticecount.count }}</span>
                        </a>
                    {% endif %}
                {% else %}
                    <a class="padding_15_i" id="a_note" href="{% url 'baseapp:main_create_log_in' %}">
                        <i id="i_note" class="glyphicon glyphicon-certificate"></i>
                    </a>
                {% endif %}
            </li>
            <li>
                <form class="navbar-form navbar-left mobile_display_none margin_top_bottom_10">
                    <div class="input-group input-group-sm">
                        <input class="form-control" placeholder="Search" id="search_desktop_input" type="text">
                        <div class="input-group-btn">
                            <i class="btn btn-default" id="search_desktop_btn"><i
                                    class="glyphicon glyphicon-search"></i>
                            </i>
                        </div>
                    </div>
                </form>
            </li>

            <li class="nav_li_last_options desktop_display_none">
                <a href="#" class="padding_15_i" id="nav_li_a_menu">
                    <i class="glyphicon glyphicon-menu-down"></i>
                </a>
            </li>

        </ul>
    </div>
</nav>

<span class="nav_badge" id="badge_home" data-u="#i_home"></span>
<span class="nav_badge" id="badge_feed" data-u="#i_feed"></span>
<span class="nav_badge" id="badge_user" data-u="#i_user"></span>
<span class="nav_badge" id="badge_note" data-u="#i_note"></span>

<div class="modal fade" id="modal_menu">
    <div class="modal-dialog modal-dialog_menu">
        <div class="modal-content modal-content_menu">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body modal-body_menu">
                {% if user.is_authenticated %}
                    <div class="row">
                        <p class="h4" align="center"><a href="{% url 'authapp:settings' %}"><span class="clickable">Settings</span></a>
                        </p>
                    </div>
                    <div class="row">
                        <p class="h4" align="center"><a href="https://twitter.com/mingu_gam" target="_blank"
                                                        rel="noopener noreferrer"><span
                                class="clickable">about/help</span></a>
                        </p>
                    </div>
                    <div class="row">
                        <p class="h4" align="center"><a href="/mingu/"><span
                                class="clickable">about question</span></a>
                        </p>
                    </div>
                    <div class="row">
                        <p class="h4" align="center"><a href="{% url 'authapp:log_out' %}"><span class="clickable">Log out</span></a>
                        </p>
                    </div>

                {% else %}
                    <div class="row">
                        <p class="h4" align="center"><a href="{% url 'baseapp:main_create_log_in' %}"><span
                                class="clickable">Log in / Create new account</span></a></p>
                    </div>
                    <div class="row">
                        <p class="h4" align="center"><a href="https://twitter.com/mingu_gam" target="_blank"
                                                        rel="noopener noreferrer"><span
                                class="clickable">about/help</span></a>
                        </p>
                    </div>
                    <div class="row">
                        <p class="h4" align="center"><a href="/mingu/"><span
                                class="clickable">about question</span></a>
                        </p>
                    </div>
                {% endif %}
            </div>
            <div class="modal-footer modal-footer_menu">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

baseapp/templates/baseapp/home.html
<!DOCTYPE html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>macawl</title>
    {% include 'others/header_static.html' %}
    {% include 'others/favicon.html' %}
    {% include 'others/header_metas.html' %}
    {% load static from staticfiles %}
    <script src="{% static 'js/navbar.js' %}"></script>
    <script src="{% static 'js/a_selected.js' %}"></script>
    <script src="{% static 'js/date_differ.js' %}"></script>
    <script src="{% static 'js/home.js' %}"></script>
    <script src="{% static 'js/suobj_populate.js' %}"></script>
</head>
<body class="light_background_color height_100">
<!--navbar start-->
{% include 'baseapp/_navbar.html' %}
{% include 'others/bootstrap_tester.html' %}

<div class="hidden" id="page_kind">home</div>
<div class="hidden" id="end_id"></div>
{% if user.is_authenticated %}
    <div class="hidden" id="user_id">{{ user.username }}</div>
{% else %}
    <div class="hidden" id="user_id"></div>
{% endif %}
<!--page info end -->

<div class="container-fluid margin_top_50">
    <div class="row">
        <div class="col-xs-12 col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-4">
            <div class="row">
                <a href="{% url 'baseapp:register_url' %}"><div class="clickable home_register_url" align="center">register url</div></a>
                <!--여기서 modal -->
                <div id="content"></div>
                <a href=""><div class="hidden clickable more_load" align="center" id="more_load">more load</div></a>

            </div>
        </div>
    </div>
</div>
{% include 'baseapp/_modal_populate.html' %}
</body>
</html>